use manutd;

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('37', '330', '<p>The world-famous forward has regularly adapted his game over the last two decades, transforming himself from the tricky, mercurial winger that arrived at United in 2003 to a poacher of the highest quality in recent years.</p>
<p>Ronaldo moved away from his home and family on the Portuguese island of Madeira to join Sporting Lisbon\'s academy and he made his first-team debut as a 16-year-old. He was being courted by several clubs, most notably Arsenal, when Sir Alex Ferguson decided to bring the talented teenager to Old Trafford after the Reds visited Sporting for a pre-season friendly in August 2003. Still spindly but with jaw-dropping footwork, Cristiano made such a great impression in that game, United&rsquo;s players on the flight home called for him to be signed. A deal was quickly done and Ronaldo was handed the iconic no.7 shirt vacated by David Beckham earlier in the summer.</p>
<p>Aged 18 and entrusted with the club&rsquo;s most famous shirt, Ronaldo made his first appearance as a substitute in a home win over Bolton Wanderers. George Best described it as the most exciting debut he&rsquo;d seen and comparisons between the two developed throughout Cristiano&rsquo;s first season at Old Trafford. His feet were quick, his body agile and his shot powerful. He could frustrate as much as he excited, his undoubted ability yet to be polished by the United coaching staff, but he ended the season with a goal in the FA Cup final against Millwall to win the first of nine trophies in six years.</p>
<p>Fellow teenage superstar Wayne Rooney joined the club in 2004 and over the next two years, the new-look team developed but titles were still going the way of Arsenal and Chelsea. After an altercation between Rooney and Ronaldo at the 2006 World Cup, it seemed the latter would end his time in England prematurely. But, led by Sir Alex, the United family closed the circle and made sure the pair felt looked after. Such faith would be repaid in spades and the Reds romped to three consecutive league titles.</p>
<p>The era of renewed success began as United thrashed Fulham 5-1 on the opening day of the 2006/07 season, with two goals from Rooney and one from Ronaldo. As Sir Alex\'s men claimed a first league title in four years, both players broke the 20-goal barrier for the first time, each of them scoring 23 in all competitions. The Reds came close to achieving a second Treble, losing in the FA Cup final and UEFA Champions League semi-final. More silverware seemed an inevitability for the team and Ronaldo was already building a collection of individual honours. By winning the PFA Players&rsquo; Player of the Year, Fans&rsquo; Player of the Year, Young Player of the Year and FWA Footballer of the Year awards, he became the first man to lift all four in the same year.</p>
<p>In the 2007/08 season, Ronaldo&rsquo;s desperate desire to be the world&rsquo;s best player drove him to new heights and United ascended with him. He scored a remarkable 42 goals as Sir Alex\'s men won a double of the Premier League title and Champions League. The Portugal international - soon to be named captain of his country - scored decisive goals time and time again in both competitions, including our only goal in the Moscow final as the Reds were crowned kings of European club football. The individual accolades all fell to Cristiano once again.</p>
<p>It soon became clear that Ronaldo sought to fulfil his childhood dream of playing for Real Madrid. Sir Alex convinced him to stay at United for one more year, enough time for him to help the Reds win a third consecutive Premier League title and become world club champions in Tokyo and, on a personal level, be crowned Ballon d&rsquo;Or winner for the first time, aged 23. After playing in a second consecutive Champions League final, as United were beaten by a brilliant Barcelona side in Rome, Ronaldo bid farewell to Manchester and moved to Madrid.</p>
<p>On 6 July 2009, 80,000 people crammed into the Santiago Bernabeu to watch the world&rsquo;s most expensive footballer being unveiled. An astonishing 450 goals in 438 games followed as Ronaldo became the all-time top goalscorer at Real Madrid. Along the way, he helped the Spanish giants to achieve the much sought-after La Decima - their 10th European Cup, in 2014 - and win 15 major trophies in total. As he did with United, Cristiano won every trophy available to Real &ndash; and most of them on more than occasion.</p>
<p>After Ronaldo had accomplished everything there was to achieve at Real Madrid, Juventus paid &euro;100m to sign him in 2018. It was the most expensive transfer by an Italian club and the highest fee ever paid for a player older than 30. He won five trophies in three years and was Serie A\'s top goalscorer last season, 2020/21, with 29 goals for the Old Lady.</p>
<p>Upon completing his second transfer to Old Trafford, the five-time Ballon d&rsquo;Or winner told United fans the club has &ldquo;always had a special place in my heart.&rdquo;</p>
<p>His former team-mate and now manager Ole Gunnar Solskjaer said: &ldquo;You run out of words to describe Cristiano. Ronaldo\'s return demonstrates the unique appeal of this club and I am absolutely delighted he is coming home."</p>
<p>As for the international stage, Ronaldo has represented Portugal at 11 major tournaments and scored in them all. He captained the Selecao to glory in the 2016 European Championships and 2019 UEFA Nations League, having worn the armband for the last 13 years. At UEFA Euro 2020, he won the Golden Boot.</p>
<p>On 1 September 2021, the day after his transfer back to United was finalised, Cristiano set a new men\'s international goals record by scoring twice for Portugal against Republic of Ireland to take his tally to 111 - two clear of the previous holder, Iran legend Ali Daei.</p>
<p>Ronaldo hit the ground running on his return to the Reds, scoring twice on his second debut in our 4-1 win over Newcastle at Old Trafford on 11 September 2021. The Portuguese superstar went on to score 24 goals in all competitions for United in 2021/22, finishing second to Mohamed Salah and Heung-min Son in the race for the Premier League Golden Boot.</p>
<p>In June, our no.7 was awarded the Sir Matt Busby Player of the Year award, equalling David de Gea\'s record of winning the accolade on four occasions. This achievement was preceded by Ronaldo\'s five Player of the Month awards and 10 Man of the Match wins, which were awarded for his match-winning exploits, such as his remarkable hat-tricks against Tottenham and Norwich.</p>
<div class="row player-content__cta ">
<p>At the age of 37, Ronaldo finished 2021/22 having made an incredible 38 appearances for the Reds in all competitions, and he\'s showing no signs of slowing down.</p>
</div>', 'Portuguese', '5 Feb 1985', 'Cristiano', 'portugal.svg', '31 Aug 2021', 'Ronaldo', '7', 'Forward', '"History has been written in the past and history will be written once again. You have my word."',  'Cristiano Ronaldo returned to Manchester United in 2021 as one of the greatest footballers of all time, with a trophy-littered career that is almost beyond the realms of belief in its consistency, longevity, and success.', 'ronaldo.jpg', 'ronaldo-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('31', '487', '<p>When Sir Alex Ferguson signed the Spaniard to replace the outgoing Edwin van der Sar, the youngster was immediately thrust into the limelight. However, having already helped Atletico Madrid to win the Europa League in 2009/10 and the UEFA Super Cup thereafter, he was more than up to the task. His first season at United saw him unfairly scrutinised by sections of the media at every turn, but he adapted to the English game to show his true colours.</p>
<p>The Madrid-born shot-stopper&rsquo;s fan-favourite status at Old Trafford has been emphasised by him claiming the Sir Matt Busby Player of the Year award on four occasions, more than any other player in United\'s history. Meanwhile, he has also collected the club&rsquo;s Player&rsquo;s Player of the Year award three times, showing the high regard his team-mates hold him in.</p>
<p>A mainstay of the Reds&rsquo; side, and occasional captain, his efforts between the posts have earned him respect from his peers as well, illustrated by the fact he has appeared in the PFA Team of the Year five times. In 2017/18, De Gea also became the first Reds keeper to win the Golden Gloves award, for keeping the most clean sheets in the Premier League, in nine years.</p>
<p>The following campaign, was his first as an ever-present in the division and contained some real highs, such as a remarkable performance in a win at Tottenham and an astounding stop against Young Boys in the Champions League. David&rsquo;s form towards the end of the campaign, mirroring that of the team in general, did slip below his usual standard but Ole Gunnar Solskjaer backed his no.1 and rightly praised his character and unquestioned ability.</p>
<p>A challenge for the Spain jersey was brought by Chelsea&rsquo;s Kepa Arrizabalaga, and, later, Unai Simon of Athletic Club.</p>
<p>De Gea signed a new long-term contract in September 2020, tying him to the club until at least June 2023, but the 2019/20 season was an indifferent one for the Madrileno. Despite plenty of typically miraculous saves &ndash; an astounding double effort at Sheffield United, and a superb performance in the Carabao Cup win against Manchester City at the Etihad Stadium &ndash; there were also some uncharacteristic lapses in concentration.</p>
<p>But David maintained his place in the United goal for the start of 2020/21, and, although there were plenty of outings for Dean Henderson, he made 28 appearances in total. Unfortunately, the last of these was a painful experience as his penalty was saved in the shoot-out against Villarreal in the Europa League final, leading to an 11-10 loss, after the 1-1 draw in Gdansk.</p>
<p>Determined to bounce back, he was soon reaching peak form again once 2021/22 got under way. Three successive Player of the Month awards at the club were testament to his quality and consistency, and this was followed by being named the Premier League Player of the Month for January. He was the first keeper since Southampton\'s Fraser Forster in 2016 to earn the trophy.</p>
<p>De Gea remained a consistent performer for the rest of the season, culminating in the Spaniard being voted United\'s Player\'s Player of the Year by his team-mates, winning the award for a record fourth time.</p>', 'Spain', '7 Nov 1990', 'David', 'spain.svg', '29 Jun 2011', 'De Gea', '1', 'Goalkeeper', 'I don’t know who is the best goalkeeper in the world at the moment, but I want to be the best.', 'David De Gea blossomed into one of the top goalkeepers in the world after joining United in 2011.', 'degea.jpg', 'degea-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('25', '29', '<p>Henderson initially started as an outfield player as a schoolboy at Carlisle United but is now regarded as one of the finest English goalies after two splendid seasons on loan with Sheffield United.</p>
<p>Each of the Cumbrian\'s temporary transfers have been huge successes, taking a step up on each occasion. This process started in 2016 with Stockport County, only for a dramatic recall from the Hatters when David De Gea was injured and, with Joel Pereira cup tied, Henderson was named on the bench for the FA Cup win at Shrewsbury Town, one of his future destinations.</p>
<p>A switch to Grimsby Town came first in August 2016, and he played seven times for the League Two outfit before getting the loan extend, only to be recalled again due to an injury to Pereira. Henderson was part of the England squad that won the Under-20 World Cup in Slovakia in June 2017 - he was an unused substitute in the final as the young Lions beat Venezuela. He has since gone on to represent his country at Under-21 level and has been drafted into Gareth Southgate\'s senior squad.</p>
<p>The 2017/18 season was a landmark one for the youngster as he performed magnificently for Shrewsbury, throughout his loan spell, appearing twice at Wembley and earning a place in the PFA Team of the Year for League One. Immensely popular with the Shrews faithful, he helped the team go all the way to the play-off final, only to lose to Rotherham United, despite Henderson\'s fine individual display.</p>
<p>The first outing at Wembley came in the EFL trophy but, again, it ended in disappointment as Lincoln City won 1-0. Nevertheless, the confident stopper enhanced his reputation considerably and was rewarded with a new contract at United.</p>
<p>However, such is the fierce competition for places in the goalkeeping department at all levels at United, he joined Championship side Sheffield United on loan for the 2018/19 season in search of more regular first-team football, on the back of his impressive stint at Shrewsbury. The move was an outstanding success as he won the Golden Glove award for keeping the most clean sheets in the division and was a key part of the Blades\' promotion to the Premier League.</p>
<p>With his stock continuing to rise, he was England\'s no.1 in the Under-21 European Championship in the summer of 2019.</p>
<p>On 26 July, the club announced that Dean had signed a new long-term contract with the Reds and returned to Sheffield United on another season-long loan, to gain valuable top-flight experience.</p>
<p>Henderson made his Premier League debut in a 1-1 draw at Bournemouth on 10 August and kept his first clean sheet in the competition the following week, when the Blades overcame Crystal Palace at Bramall Lane. One of the side\'s stand-out performers all season, he was voted their Young Player of the Year and cemented his status as one of the division\'s most reliable keepers.</p>
<p>On 26 August 2020, he signed a new long-term contract with his boyhood club, committing his future to the Reds until 2025 with the option of a further year.</p>
<p>Henderson made his Reds first-team bow at Luton in the Carabao Cup in September 2020, keeping a clean sheet as Ole Gunnar Solskjaer\'s side progressed to the fourth round with a 3-0 victory, and followed that up with a first appearance for the senior England side, coming on as a half-time substitute during the Three Lions\' 3-0 friendly win over Republic of Ireland on 12 November 2020.</p>
<p>By the end of the season, he had racked up 26 appearances for the Reds and shown his capabilities. However, he suffered a setback when being forced to withdraw from England\'s Euro 2020 squad due to injury and then contracted COVID-19 which affected his pre-season preparations. Once fit again, he was able to compete with David De Gea for the gloves but played only three first-team games in the 2021/22 season, against West Ham, Young Boys and Middlesbrough.</p>', 'England', '12 Mar 1997', 'Dean', 'england.svg', '1 Aug 2013', 'Henderson', '26', 'Goalkeeper', '"I work hard every single day to be a better version of myself. At the end of the day, the only competition I’ve got is myself."', 'The highly rated keeper joined the Reds as a 14-year-old and has proved his qualities at Premier League level.', 'henderson.jpg', 'henderson-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('27', '196', '<p>In June 2015, he scored in the penalty shoot-out in the European Under-21 Championship final to help earn his country a notable first international triumph.</p>
<p>Lindelof had only been introduced to the squad as a late call-up but performed with distinction at right-back, earning a place in UEFA\'s Team of the Tournament. It helped provide added impetus to his club career as he forced his way into the senior Benfica side and enjoyed experience in the domestic top flight and Champions League.</p>
<p>Patience has been important for the Scandinavian, who burst into Vasteras\' first team when only 16 years old. He helped his local side gain promotion but left when Benfica came calling in 2012. The Lisbon giants had seen his potential in Sweden\'s Under-16s and Under-17s and made their move.</p>
<p>Still only 17, Lindelof understandably had to wait for an opportunity and cut his teeth with the B team, before emerging as one of Europe&rsquo;s most exciting young defenders with the senior side.</p>
<p>Winning trophies became something of a habit during his time in Portugal, as he collected three league titles, two Portuguese Cups, one League Cup and one Super Cup. This being in addition to his European Under-21 Championship medal, of course.</p>
<p>In 2017, the composed centre-back signed a four-year deal at United, with the option of a further year. The defender ended his maiden campaign in England with 29 appearances and a number of impressive performances towards the end of the season, including a Man-of-the-Match display against Arsenal in April.</p>
<p>After reaching the quarter-finals of the 2018 World Cup with Sweden, he continued his development in the 2018/19 season, maintaining a consistent level of form that endeared him to the Old Trafford faithful. Lindelof\'s fine performances saw him named the club\'s Player of the Month for November - when he was also named Sweden\'s Player of the Year at an awards ceremony in Stockholm.</p>
<p>Two months later, he scored his first goal in a red shirt, netting a late equaliser against Burnley. A groin injury hampered his progress in the final weeks of the season, but Victor still emerged as one of the biggest plusses of the campaign. He came a close second, behind Luke Shaw, in the votes for the Players\' Player of the Year and Sir Matt Busby Player of the Year awards respectively.</p>
<p>In the 2019/20 campaign, the Swede featured in 35 Premier League matches, forming a solid partnership with United skipper Harry Maguire in a season where United finished third in the table and thereby qualified for the Champions League. In December 2019, he scored his second goal for the club in a 2-2 draw with Aston Villa at Old Trafford and he was a regular presence the following season, as the Reds came second and made it to the Europa League final.</p>
<p>Lindelof\'s stature grew even further in the 2021/22 season, as became a trusted partner for both Harry Maguire and Raphael Varane. The Swede regularly demonstrated his composure on the ball and coupled that with stern defensive resilience to become a valuable asset for Ole Gunnar Solskjaer and interim manager Ralf Rangnick.</p>
<p>Our Swedish centre-back made 35 appearances in all competitions in 2021/22, producing impressive performances away from home against the likes of Villareal and Spurs. He even started at right-back when we visited Atletico Madrid in the Champions League, and showed his versatility by putting in a competent display.</p>', 'Sweden', '17 Jul 1994', 'Victor', 'sweden.svg', '1 Jul 2017', 'Lindelof', '2', 'Defender', 'United are one of the biggest clubs in the world and always want to win titles. That’s also my goal.', 'Dealing with pressure is something that appears to come naturally to unflappable Swedish defender, Victor Lindelof.', 'lindelof.jpg', 'lindelof-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('28', '113', '<p>Bailly\'s quality as an aspiring footballer was spotted by Spanish outfit Espanyol during a youth tournament held in Burkina Faso. He was signed by the Catalan club in December 2011 and joined their youth system at 17, but it was 10 months before he received a work permit enabling him to play.</p>
<p>Once his papers arrived, he became a regular in the Espanyol B team, playing under the name of Eric Bertrand, until deciding to use his mother&rsquo;s surname, Bailly, instead. He went on to become a regular in Espanyol&rsquo;s first team before his powerful displays in the heart of defence earned him a move to Villarreal in January 2015.</p>
<p>The 6ft 1in defender&rsquo;s first big move came during the 2015 Africa Cup of Nations, in which he netted his spot-kick in the final penalty shoot-out as Ivory Coast beat Ghana to claim their second title.</p>
<p>After a slow start at Villarreal, he made himself a mainstay in the club&rsquo;s defence the following season. His tough tackling and no-nonsense approach helped the Yellow Submarine finish fourth in La Liga and reach the Europa League semi-finals.</p>
<p>Bailly secured a move to Old Trafford ahead of the 2016/17 campaign and his versatility proved crucial, as he made 38 appearances across all competitions and featured at both centre-back and right-back.</p>
<p>Although he missed the Europa League final through suspension, he did play the full 90 minutes at Wembley as United overcame Southampton to win the League Cup.</p>
<p>Bailly&rsquo;s trademark tough tackling has made him a fan favourite in Manchester, but his impressive ball-playing ability and anticipation skills have taken his game to the next level.</p>
<p>Injury meant the defender had a very stop-start campaign in 2017/18, but when available Bailly was as dependable as ever and even managed to notch his first United goal in a 4-0 win at Swansea.</p>
<p>Although he continued to impress when on the pitch, a combination of injuries, a suspension following his red card against Bournemouth in December, and the form of Chris Smalling and Victor Lindelof restricted Bailly to 18 appearances in all competitions in 2018/19.</p>
<p>Unfortunately, a knee injury sustained against Chelsea at the end of April brought a premature end to his campaign and also ruled him out of the Africa Cup of Nations with his country.</p>
<p>After returning to action in pre-season, Eric suffered a further blow when he injured his knee again during the International Champions Cup win over Tottenham in July 2019. He underwent an operation and Ole Gunnar Solskjaer confirmed he would be out for four to five months.</p>
<p>Eric returned seven months later against the same opposition, in an impressive 2-0 win at Stamford Bridge, during which he was one of the outstanding performers. Unfortunately, the COVID-19 lockdown stalled his promising run of form, but he played a full part in the delayed close to 2019/20, helping United to a third-place Premier League finish and the semi-finals of the Europa League.</p>
<p>After making his 100th appearance for the club against Milan in March, he signed a new contract with the Reds in April 2021 and started in the Europa League final defeat to Villarreal the following month. The centre-back made his first appearance of the 2021/22 term in the Carabao Cup game with West Ham United.</p>
<p>Bailly\'s last start of that season came in United\'s 3-1 win over Burnley in December, before he went to represent Ivory Coast at the Africa Cup of Nations in January 2022. Upon his return, the defender suffered an ankle injury which kept him out for three weeks. After regaining fitness, Bailly competed with fellow centre-backs Harry Maguire, Raphael Varane and Victor Lindelof for the remainder of the season.</p>', 'Ivory Coast', '12 Apr 1994', 'Eric', 'ivorycoast.svg', '8 Jun 2016', 'Bailly', '3', 'Defender', 'To play football at the highest level is all I have ever wanted to do.', 'Eric Bailly joined Manchester United from Villarreal in the summer of 2016 and quickly made a name for himself at Old Trafford.', 'bailly.jpg', 'bailly-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('30', '229', '<p>A dogged, brave and talented centre-back, and a player who can also play at full-back and drop into midfield when needed, Jones has been unlucky to see his United career punctuated by spells of injury and illness. But that hasn&rsquo;t stopped him becoming an important player for both club and country.</p>
<p>Jones put in a number of accomplished displays during his first season with the Reds, but injury robbed him of almost half a season the following year, in 2012/13. However, he returned to the side to help United win the Premier League title and claim his first trophy with the club.</p>
<p>A regular during the 2013/14 campaign, he earned a place in England&rsquo;s 2014 World Cup squad and he impressed at centre-back during 2014/15 despite his appearances being further restricted by injuries.</p>
<p>The signing of a new long-term contract in June 2015 emphasised his importance to the United cause and he was part of the FA Cup-winning squad against Crystal Palace in May 2016.</p>

<p>Injury once again disrupted the start of his first campaign under Jose Mourinho in 2016/17 but he still helped make it a memorable season as United claimed the League Cup and Europa League trophies.</p>
<p>The centre-back enjoyed one of his best campaigns in a red shirt in 2017/18 and was one of the first names on the team sheet. He finished the season with 15 shutouts from 25 games and consequently earned a place in England\'s 2018 World Cup squad.</p>
<p>Jones had a frustrating start to 2018/19 and spent much of the first half of the campaign sidelined through injury. But he returned to prominence thereafter and was a central part of the Reds\' mid-season resurgence following Ole Gunnar Solskjaer\'s appointment.</p>
<p>By the end of the season, Phil had penned a new long-term contract, much to the delight of his manager. &quot;Phil knows what it takes to be a Manchester United player,&quot; noted Solskjaer. &quot;He has won the Premier League, FA Cup and Europa League and is one of the senior players within the team.&quot;</p>
<p>After almost two years on the sidelines with injury, Jones made his return to the United first-team on 3 January 2022, when the Reds hosted Wolverhampton Wanderers at Old Trafford. Our centre-back featured a further three times in the Premier League and once in the FA Cup before the end of the season.</p>', 'England', '21 Feb 1992', 'Phil', 'england.svg', '1 Jul 2011', 'Jones', '4', 'Defender', 'I just love to defend. I want to stop goals going in the net.', 'Having impressed in a handful of performances against the Reds for Blackburn Rovers, the powerful, energetic defender chose Old Trafford over several alternative destinations in the summer of 2011.', 'jones.jpg', 'jones-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('29', '144', '<p>However, his route to the top has not always been an easy one.</p>
<p>The Sheffield-born star came through the youth system at his hometown club Sheffield United. A resilient and tough-tackling defender, Maguire progressed into the first team at the age of 18 and made his debut for the Blades against Cardiff City in April 2011.</p>
<p>The early signs of Harry&rsquo;s quality were clear to see. Despite being introduced as a half-time substitute in that Championship clash with the Bluebirds, the then-teenager was named Man of the Match.</p>
<p>Sadly, that campaign ended in relegation for Sheffield United, yet Maguire, who featured five times in his first season, had impressed the locals at Bramall Lane. He would go on to spend three more years with the Yorkshire outfit and make 166 appearances for the Blades, while netting on 12 occasions.</p>
<p>A host of top-tier sides had been monitoring Maguire&rsquo;s development, but it was one of United\'s finest centre-backs of all time who ultimately managed to prize Harry from his boyhood club. However, after signing the youngster at Hull City, Steve Bruce was wary of blooding him into the side, ahead of experienced defenders such as former Red James Chester, Curtis Davies and Michael Dawson.</p>
<p>After playing just a handful of games in the first half of the 2014/15 campaign, Maguire was sent on loan to struggling Wigan Athletic, who, like Hull, were relegated that season. But with Maguire at the heart of defence, the Tigers instantly returned to the Premier League in the following campaign.</p>
<p>Aged 23 at the time, Harry was five years into his professional career and had already faced his fair share of adversity. While Hull again failed to beat the drop in 2016/17, Maguire&rsquo;s individual performances caught the eye. In fact, so impressive were Harry\'s displays, he was voted the club&rsquo;s Player of the Year, earned a move to Leicester and was called up to Gareth Southgate&rsquo;s England squad.</p>
<p>Always a colossal presence at the back, it was during his time with Leicester that Maguire developed the passing side to his game, which he is now so eulogised for among Premier League aficionados. In two years at the Foxes, Harry established himself as one of the division&rsquo;s standout centre-backs, while also becoming a cornerstone of England&rsquo;s recent World Cup and Nations League campaigns.</p>
<p>He has also proved effective at the other end of the pitch and famously headed home the Three Lions&rsquo; opener against Sweden in the 2018 World Cup quarter-final, while scoring five goals for the Foxes. Maguire even netted an injury-time equaliser against United in December 2017 to earn his former employers a 2-2 draw.</p>
<p>Harry&rsquo;s rise through the divisions, while also overcoming the occasional moment of hardship, has seen him mature into an all-round leader - one the world&rsquo;s top sides simply could not overlook.</p>
<p>But it was the allure of playing for a club of such stature and pedigree that ultimately convinced Harry to swap the East Midlands for Old Trafford, completing his move to the Reds on 5 August 2019.</p>
<p>It didn\'t take long for Maguire to make an impact on the dressing room and, after wearing the captain\'s armband on a handful of occasions, he was appointed as United\'s new permanent skipper on 17 January 2020 following Ashley Young\'s departure to Inter Milan. Nine days later, Harry led by example in the Emirates FA Cup win over Tranmere Rovers as his first goal for the club triggered an eventual 6-0 triumph.</p>
<p>The skipper then scored an important header at Stamford Bridge as United beat Chelsea in a crucial game for the Champions League spots. He also got on the scoresheet in the FA Cup as Norwich were beaten late at Carrow Road as United reached the semi-final of the tournament.</p>
<p>Maguire remained a mainstay in the United defence throughout the season which ended with a third-place finish and Champions League qualification. Both were secured with a 2-0 win at his former home ground, the King Power Stadium, on the last day of the 2019/20 campaign.</p>
<p>There was further improvement the following term, with Ole Gunnar Solskjaer\'s side finishing second, but Maguire missed the end of the season - and the Europa League final - with injury.</p>
<p>Despite suffering some niggling injuries throughout the season, Maguire racked up 37 appearances for United in 2021/22. Trusted by Solskjaer - and then interim manager Ralf Rangnick - Harry made 35 starts in what ended up being a disappointing season for the Reds as we finished sixth in the Premier League.</p>
<p>Maguire contributed to some of our most crucial victories of the season, such as his strong defensive display in our 1-0 win over West Ham. The skipper also got on the scoresheet twice in 2021/22, slotting home a Champions League goal against Atalanta and powering in a header away to Leeds in the Premier League.</p>', 'England', '5 Mar 1993', 'Harry', 'england.svg', '5 Aug 2019', 'Maguire', '5', 'Defender', 'It\'s an amazing club. It\'s a club I\'ve always watched and I always looked up to when I was younger.', 'Harry Maguire has risen through the leagues to establish himself as one of the most reliable centre-backs in the game.', 'maguire.jpg', 'maguire-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('29', '29', '<p>With three La Liga titles, four Champions League trophies, a World Cup winners&rsquo; medal and numerous other honours on his CV, it&rsquo;s easy to forget that the quick and classy ball-playing centre-back is still only 28.</p>
<p>But then Varane has always been experienced beyond his years. Born in April 1993, he signed his first professional contract at boyhood club Lens just after turning 17, on the back of an impressive season playing with older team-mates at Under-19 level.</p>
<p>Lens boss Jean-Guy Wallemme was so convinced by his young charge&rsquo;s talent that, when faced with a defensive injury crisis, he threw the tall and composed Varane in as a starter for a November 2010 clash with Montpellier.</p>
<p>A rare clean sheet for the Ligue 1 strugglers followed and, even though that season would end in relegation, Europe&rsquo;s top clubs had been alerted to the potential of the teenager, who made 23 top-flight appearances and even showed his leadership capabilities when captaining the side in their closing game.</p>
<p>Sir Alex Ferguson, looking for a long-term replacement for Rio Ferdinand and Nemanja Vidic, was very interested and, according to his book, our legendary boss personally got involved in the negotiations, only for Real Madrid and new sporting director Zinedine Zidane to step in.</p>
<p>A thoughtful, studious figure &ndash; he supposedly asked Zidane to call him back when gauging his interest in the Madrid move, as he was revising for his economics exams &ndash; Varane joined the Bernabeu club in late June, starting a 10-year association in which he was, largely, a fulcrum in one of the Spanish club&rsquo;s most storied sides.</p>
<p>After being a bit-part player in the 2011/12 La Liga success, the Frenchman soon established himself as centre-back alongside Sergio Ramos, impressing in Europe to such an extent that, in 2013, he was named in Marca&rsquo;s &lsquo;best-ever Real Madrid foreign XI&rsquo;, despite playing fewer than 50 games.</p>
<p>Any accusations of those plaudits being premature were put to bed a year later, when Varane helped Los Blancos to the fabled &lsquo;La Decima&rsquo; &ndash; a 10th Champions League triumph &ndash; as they dramatically beat city rivals Atletico Madrid in Lisbon.</p>
<p>Aged 21, Varane virtually completed the set of major club trophies with Club World Cup success later that month, but there was more to come, especially after Zidane replaced Rafa Benitez in the Bernabeu hot seat in January 2016.</p>
<p>Raphael was absent for the next Champions League triumph later that year through injury but was again a key member of the side as Real became the first club since Bayern Munich in the 1970s to win three consecutive European Cups, with further successes in 2017 and 2018.</p>
<p>Zidane, who had also won La Liga with his former club side in 2017, announced his departure following that feat, culminating in a poor 2018/19 campaign, but returned to mastermind another title, with Varane the heartbeat of an experienced team alongside the likes of Ramos, Karim Benzema and Toni Kroos.</p>
<p>Just over 10 years after the highly-rated teenager left France, Varane departs Madrid as one of Real&rsquo;s most decorated overseas players, but he will also take his place alongside the likes of Laurent Blanc, Marcel Desailly and Lilian Thuram in the pantheon of top-class French defenders.</p>
<p>A youth international at various levels, he made his full debut for Les Bleus in 2013 and went to the following year&rsquo;s World Cup, where he was one of three shortlisted for the tournament&rsquo;s Best Young Player award.</p>
<p>The youngest player to captain France in 104 years, injury caused him to miss out on the run to the Euro 2016 final on home soil, but he more than made up for that two years later in Russia.</p>
<p>Didier Deschamps&rsquo;s men were crowned world champions, with Varane playing every minute of the tournament and scoring the key opening goal in the quarter-final victory over Uruguay and that ability to come good in the clutch moments &ndash; without ever stealing the headlines &ndash; has defined Raphael&rsquo;s career.</p>
<p>He caught the eye at Real especially with his performances in the latter stages of the Champions League, with Los Blancos making it to the final four in all but two of his seasons there. But Cristiano Ronaldo and Ramos were usually the main men, with Varane happy to quietly get on with it.</p>
<p>&ldquo;Tall and athletic, there&rsquo;s a presence about Varane, an understated authority,&rdquo; writes Spanish football expert Sid Lowe. &ldquo;But not exactly the loudest in the dressing room, nor immediately charismatic or flamboyant, he doesn&rsquo;t demand attention, on or off the pitch. He just plays: regularly for a decade at the most unforgiving place, remember.&rdquo;</p>
<p>Of course, Old Trafford isn&rsquo;t exactly immune to the spotlight either. But few overseas arrivals have come better equipped to succeed than Varane, who really has seen and done it all.</p>
<p>Unveiled on the pitch prior to United\'s 5-1 win over Leeds in August 2021, Varane made his Reds debut two weeks later at Molineux. Following his first United appearance, the Frenchman went on to star 29 times for the Reds in his debut season.</p>
<p>Varane\'s first season was disrupted by injuries, forcing the centre-back to miss 16 matches in all competitions. However, when he was fit, the Frenchman oozed class.</p>
<p>Varane also managed to notch his first goal for United in his debut season, volleying home from a corner in our comfortable 3-0 win over Brentford in May. After impressing in his first year at Old Trafford, supporters will be eager to see what the Frenchman can do next.</p>', 'French', '25 Apr 1993', 'Raphael', 'france.svg', '14 Aug 2021', 'Varane', '19', 'Defender', '"I came here because I wanted new emotions and it was exactly what I expected and bigger."', 'One of the world’s best defenders over the last decade, Raphael Varane’s track record speaks for itself.', 'varane.jpg', 'varane-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('23', '65', '<p>The full-back has been turning heads with his footballing ability, since the age of six, when he joined Fintas Academy in his hometown of Braga.</p>
<p>With a host of Portugal&rsquo;s biggest clubs monitoring the defender, Dalot joined Porto&rsquo;s youth system in 2008 at the age of nine and blossomed into a typical modern full-back.</p>
<p>The Portuguese is blessed with natural pace, an appetite to attack and has a fine cross in his armoury of skills.</p>
<p>Having been capped by Portugal at youth level from Under-15s to Under-21s, Diogo has already tasted success on the international stage - notably, at the Under-17 European Championship in 2016, when he scored two crucial goals during his five appearances and was named in the Team of the Tournament.</p>
<p>In 2014/15, a brief loan spell at Padroense in the Portuguese Second Division, and several impressive displays for Porto&rsquo;s Reserves team, paved the way for Dalot to progress into the first team.</p>
<p>He only made his senior debut for the club in October 2017 and didn&rsquo;t appear in the Portuguese Primeira Liga until February 2018, but his early form gave real signs of encouragement.</p>
<p>Diogo went on to make 33 appearances in the 2017/18 season - including one in the knockout stages of the Champions League - and he registered four goals and eight assists. Such was the teenager&rsquo;s undoubted ability, former manager Jose Mourinho acted quickly to secure the signature of his Portuguese compatriot.</p>
<p>He was one of three new additions at Old Trafford in the summer of 2018, but joined the club with a long-term knee injury which prevented him from making his first-team debut until mid-September, during a 3-0 Champions League win against Young Boys.</p>
<p>It was a solid start from Dalot and one he repeated a week later when he played in front of the Old Trafford faithful for the first time, in a Carabao Cup tie against Derby County. Dalot finished his first term in England with a healthy 23 appearances to his name and was selected in high-profile matches against Arsenal, Liverpool and Tottenham Hotspur.</p>
<p>He also played a huge part in United&rsquo;s progression to the Champions League quarter-final stage. It was the defender&rsquo;s bullet of a shot that was adjudged to have hit Presnel Kimpembe on the arm, and resulted in our injury-time winner against Paris Saint-Germain in the last 16.</p>
<p>Dalot scored his first goal for United in a 6-0 FA Cup win at Tranmere Rovers in January 2020, as he made 11 appearances in his second season at the club.</p>
<p>The Portuguese full-back joined AC Milan in Serie A for the 2020/21 season, with the deal being announced at the beginning of October. The move was a success, and he even played against his parent club in the Europa League, before helping the Rossoneri qualify for the Champions League via second spot in Serie A.</p>
<p>After representing his country at the European Championship finals, he had a mission to make his mark at Old Trafford and scored a header in a pre-season friendly win over Everton. Dalot obtained much more game-time following the arrival of interim manager Ralf Rangnick, and that continuity and rhythm led to consistently high performances at right-back.</p>
<p>By the end of 2021/22, Dalot had made 29 appearances in all competitions for the Reds, starting nine of the final 10 Premier League matches of the season. He was also regularly selected in Portugal\'s squad for international friendlies and Nations League matches.</p>', 'Portugal', '18 Mar 1999', 'Diogo', 'portugal.svg', '6 Jun 2018', 'Dalot', '20', 'Defender', 'I will give everything for this club, for this shirt and, hopefully, help the club to win. That’s the most important thing.', 'Diogo Dalot remains a promising talent and has already achieved so much in his fledgling career.', 'dalot.jpg', 'dalot-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('26', '213', '<p>The talented defender&rsquo;s Southampton career began in 2004, when he joined the south-coast outfit as a 10-year-old, after being released by boyhood favourites Chelsea.</p>
<p>Shaw then rose through the ranks and made his first-team debut in 2012, aged 16. He went on to nail down the left-back spot at the club, as he flourished under the tutelage of Nigel Adkins and Mauricio Pochettino, eventually amassing 67 appearances for the Saints before leaving for United.</p>
<p>Although injuries disrupted his debut campaign at Old Trafford, when he made just 20 first-team outings across all competitions, the defensive livewire convinced many observers that he could become an important cog in the Reds\' machine. However, the left-back endured a nightmare 2015/16 campaign, as he suffered a horrific leg break in a Champions League game with PSV Eindhoven, which ruled him out for the season.</p>
<p>The England international returned to training in April 2016 and was desperate to impress new boss Jose Mourinho in 2016/17 but, sadly, it was largely a season of niggling injuries that hampered his progress. He managed to make 19 appearances across all competitions and repaid his manager&rsquo;s faith with some strong showings, before a foot problem ended his campaign prematurely.</p>
<p>The following season proved just as frustrating for Shaw and again he only made 19 first-team appearances. However, the defender was always reliable when called upon and played a significant role in United&rsquo;s run to the FA Cup final.</p>
<p>The 2018/19 campaign proved to be much more fruitful for Shaw, at least on a personal level. He began the season in superb form, scoring the first goal of his senior career in the Reds&rsquo; opening-day win over Leicester City and winning the club\'s Player of the Month awards for both August and September. His impressive displays earned him a recall to the England squad in August and two months later he was rewarded with a new contract at United.</p>
<p>After picking up a third Player of the Month prize in March 2019, Shaw went on to win the Sir Matt Busby Player of the Year award, as voted for by the supporters, and the Players\' Player of the Year accolade.</p>
<p>He repeated the later success in 2021, at the end of a stellar campaign which saw Luke emerge as one of the Premier League\'s best left-backs and secure a place in Gareth Southgate\'s 26-man selection for the delayed European Championships.</p>
<p>Following his heroic exploits at the European Championships, Shaw hit the ground running for United in the 2021/22 season. Our left-back started 11 of our first 12 Premier League matches and played a key role in our progression from the Champions League group stage.</p>
<p>However, a string of injuries led to Shaw featuring only 11 more times for the Reds between January and the end of the season, with the England international missing the Premier League run-in.</p>', 'England', '12 Jul 1995', 'Luke', 'england.svg', '27 Jun 2014', 'Shaw', '23', 'Defender', 'I’ve got the freedom to play and that gives me the confidence in what I want to do to help the team.', 'Luke Shaw joined Manchester United from Southampton in June 2014, making him one of the Reds’ longest-serving players.', 'shaw.jpg', 'shaw-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('29', '50', '<p>The 27-year-old Brazilian is a true all-rounder; as comfortable flying down the wing as he is stifling opposition attacks. Telles has also shown his aptitude in front of goal, and his conversion statistics would be impressive for an offensive winger, let alone a defender.</p>
<p>Born in Caxias do Sul on 15 December 1992, Telles came through the youth system at Brazilian side Juventude, and made his debut in 2011, in the fourth tier of his native country. However, it was immediately obvious that the youngster had a big future ahead of him, and a move to Gremio &ndash; in Brazil&rsquo;s top division &ndash; soon followed.</p>
<p>At the Porto Alegre-based club, Alex established himself as one of the world&rsquo;s most promising full-backs and, having missed just two league games in the 2013 season, was selected in the Brasileiro Serie A Team of the Season.</p>
<p>The left-back seemed certain to tread a familiar path for young Brazil stars and make the move to Europe. That&rsquo;s exactly what he did after just one season in the Brazilian top flight, and it was Galatasaray who secured Alex&rsquo;s services during the January 2014 transfer window.</p>
<p>In the Turkish Super Lig, Telles continued to excel. In a year and a half with the Istanbul giants, he won the Turkish Cup twice and the title in 2014/15. The man from southern Brazil also had his first taste of European football and faced English sides Chelsea and Arsenal in successive seasons in the Champions League.</p>
<p>The following campaign saw Telles join Internazionale on a season-long loan, and gain his first experiences playing in one of Europe&rsquo;s &lsquo;top five&rsquo; leagues. His impressive showings in Italy alerted the attentions of Porto, who signed the full-back on a permanent deal in 2016.</p>
<p>In four years at the Portuguese club, Telles racked up nearly 200 appearances and helped Porto win league titles in 2017/18 and 2019/20.</p>
<p>The defender, who can also operate in midfield, has become accustomed to facing Europe&rsquo;s top sides and came up against Liverpool, Juventus and RB Leipzig on Champions League duty during his time at Porto.</p>
<p>Telles&rsquo;s development in recent years has been evident for regular followers of Portuguese football. The Brazilian was selected in the Primeira Liga Team of the Year in each of his last three seasons at Porto and was also voted as the club&rsquo;s Player of the Season in 2017/18. But it was his final year with the Dragoes that he really caught the attention of Europe&rsquo;s top clubs.</p>
<p>From left-back, Telles contributed an incredible 11 league goals and eight assists in just 31 appearances. Not that his contributions were limited to the offensive areas of the field, and Alex played a vital role in a defence that conceded just 22 league goals throughout the campaign.</p>
<p>An accomplished shooter from distance, with an excellent crossing range and an ability to rapidly bypass opposition defenders, Telles established himself as one of the most-sought-after full-backs in Europe before joining United in October 2020.</p>
<p>His excellent displays also earned him a maiden call-up to the senior Brazil squad in March 2019, and Alex won a first cap in a 1-1 draw with Panama.</p>
<p>Just weeks before signing for the Reds, Telles was once again selected by his country, for key World Cup qualifiers against Bolivia and Peru.</p>
<p>In his first season at the club, the Brazilian left-back accumulated 24 appearances in all competitions and was a regular in our Europa League campaign as the Reds reached the final.</p>
<p>Injury ruled Telles out of the first four Premier League matches of the 2021/22 season, and the full-back had to be patient for his chance to start regularly. As the season progressed, the Brazilian international re-established himself as a first-team regular, making 25 appearances in all competitions and starting 10 of the last 12 Premier League matches.</p>
<p>While Telles only scored one goal in 2021/22, his stunning volley in our 2-1 win over Villareal came third in UEFA\'s 2021/22 Champions League Goal of the Tournament vote.</p>', 'Brazilian', '15 Dec 1992', 'Alex', 'brazil.svg', '5 Oct 2020', 'Telles', '27', 'Defender', 'This is a once-in-a-lifetime opportunity. I’m going to give everything to fight for the club.', 'In Alex Telles, Manchester United recruited a hugely experienced player who had already demonstrated his ability as a left-back in some of European football’s most competitive leagues.', 'telles.jpg', 'telles-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('24', '126', '<p>The talented England Under-21 international took to Premier League life like a duck to water at Palace.</p>
<p>It barely mattered that he was still a rookie in the right-back position, having spent much of his time in the Eagles&rsquo; Academy operating further up the flank or even as a forward.</p>
<p>Palace coach Kevin Keen suggested him as an option in defence when they had a training game and he marked ex-Reds winger Wilfried Zaha so well, the experiment continued.</p>
<p>Even if he never saw himself as a defender back then, Wan-Bissaka displayed great application and soon looked a natural in the role. Described as &ldquo;dogged and determined&rdquo; by Roy Hodgson, and a &ldquo;cool customer&rdquo; by Under-23s coach Richard Shaw, the youngster never looked back after making his debut against Tottenham Hotspur in February 2018.</p>
<p>An excellent performance against United soon followed, deputising for Tim Fosu-Mensah when the Dutchman was ineligible due to the terms of his loan move, and he deservedly won the club&rsquo;s Young Player of the Year award in the 2017/18 campaign.</p>
<p>A year later, he picked up the senior prize after a stellar season for the south Londoners, registering outstanding statistics. Indeed, he outperformed every other Premier League full-back for clearances, tackles won, tackle success-rate, take-ons and interceptions. The speculation surrounding his future had, by then, already started with United reckoned to be long-time suitors.</p>
<p>Involvement in the Under-21 European Championship with England meant any move, however, would have to be on hold.</p>
<p>He had initially represented Congo, where his father was born, at Under-20 level in a friendly against England&rsquo;s Under-17s at St George&rsquo;s Park, but has since been successfully integrated into the Three Lions\' set-up.</p>
<p>A deal with United was concluded following England&rsquo;s exit from the finals in Italy and San Marino, enabling Wan-Bissaka to sign on the dotted line.</p>
<p>&ldquo;This club is known for winning trophies and I want to be a part of that, to win my first,&rdquo; Aaron told us in his opening interview. &ldquo;I can see that the fan-base is huge and they support the team through thick and thin. I am going to give everything for the club and for the fantastic fans and I can&rsquo;t wait to get started.&rdquo;</p>
<p>Aaron completed his move on 29 June 2019, before recharging his batteries on holiday ahead of linking up with his new colleagues later in the summer.</p>
<p>A determined right-back, he scored his first United goal at Newcastle in October 2020 and went on to make his 100th appearance for the club during the Europa League final defeat to Villarreal.</p>
<p>In 2021/22, Wan-Bissaka made a further 26 appearances for the Reds, starting the first 13 consecutive Premier League matches of the season. Unfortunately, a hand injury and illness halted the right-back\s progress and his appearances for the remainder of the season were sporadic.</p>', 'England', '26 Nov 1997', 'Aaron', 'england.svg', '29 Jun 2019', 'Wan-bissaka', '29', 'Defender', 'Every kid wants to play for a team like this. It\'s an honour to represent this club.', 'Aaron Wan-Bissaka became Manchester United’s second signing of the summer transfer window in June 2019 when he joined from Crystal Palace.', 'awb.jpg', 'awb-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('29', '157', '<p>The Belo Horizonte-born star had proved his capabilities long before his move to Old Trafford, by playing a key role in Shakhtar Donetsk&rsquo;s successful title defence in Ukraine the previous year, and with his impressive displays in the 2017/18 UEFA Champions League.</p>
<p>As a youngster, Fred spent time at Atletico Mineiro and Porto Alegre in his native Brazil, before his rise into professional football really took off when he made the switch to Internacional in 2010. During his successful two-year spell at Est&aacute;dio Beira-Rio, the dynamic midfielder won back-to-back local state championships, as well as the Recopa Sudamericana.</p>
<p>His influential performances attracted the attention of a number of European clubs and Shakhtar came calling in 2013.</p>
<p>Fred spent five successful seasons with the club, where he scored 14 goals in 156 games and won 10 major trophies &ndash; three league titles, three Ukrainian Cups and four Ukrainian Super Cups.</p>
<p>Before joining the Reds, he had already experienced a brief taste of playing at Old Trafford, with Shakhtar Donetsk in a Champions League group game against United, when the Reds won 1-0 thanks to a Phil Jones goal in December 2013.</p>
<p>On the international stage, Fred made his Brazil debut in 2014 and was called up for the Copa America a year later, as he was again for the 2018 World Cup.</p>
<p>Just over a month after Brazil&rsquo;s quarter-final exit, Fred made his Reds debut in the first game of the 2018/19 season, against Leicester City.</p>
<p>The midfielder took quickly to life in English football and produced some fantastic performances in the opening month of the campaign, including in the 2-1 victory against the Foxes, and was nominated for the club&rsquo;s August Player of the Month award.</p>
<p>He followed that by bagging his first United goal in our 1-1 draw against Wolverhampton Wanderers in September, but had to be patient for further first-team opportunities in the coming weeks and months.</p>
<p>It wasn&rsquo;t until Ole Gunnar Solskjaer took up the managerial reins in December that Fred again featured regularly. Arguably, his best performance of his maiden campaign at United came in our famous comeback win against Paris Saint-Germain in March, when he managed to nullify the threat from fellow South American Leandro Paredes.</p>
<p>Fred enjoyed his best season yet in 2019/20, forging a useful partnership with Scott McTominay in central midfield during the injury-enforced absence of Paul Pogba, and was even named Player of the Month in January 2020.</p>
<p>He scored a double against Club Brugge in the Europa League last 32 &ndash; his first strikes in Red since his maiden goal against Wolves &ndash; and remained a trusted lieutenant for Ole Gunnar Solskjaer throughout, making 48 appearances.</p>
<p>He matched that tally in his third season with the club and added a second Premier League goal, scoring the equaliser in a memorable comeback victory over Tottenham Hotspur in north London.</p>
<p>Fred enjoyed arguably his best season in a United shirt in 2021/22. The diligent Brazilian scored four goals and assisted six in a productive year that saw him reach the milestone of 100 Premier League appearances.</p>
<p>The Brazilian scored in his 100th Premier League match to earn the Reds a draw against Leicester, while also netting goals against Crystal Palace and Leeds, and impressing as a more dynamic attacking force. Now clearly at home in Manchester, he will look to push on after finishing third in the Sir Matt Busby Player of the Year vote in 2021/22.</p>', 'Brazil', '5 Mar 1993', 'Fred', 'brazil.svg', '21 Jun 2018', '', '17', 'Midfielder', '"I will never forget how I felt the day I made my debut at Old Trafford. It was just fantastic."', 'Fred joined Manchester United in the summer of 2018, while representing Brazil at the World Cup finals in Russia.', 'fred.jpg', 'fred-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('27', '126', '<p>While the likes of Cristiano Ronaldo and Nani made their names in Portugal, Fernandes spent the first five years of his career in Italy.</p>
<p>A youth product at Boavista, the midfielder signed for Serie B club in Novara in August 2012, at the age of 17. Initially suffering from homesickness, he eventually grew into his new environment, teaching himself Italian and helping the Blues to fifth position, before joining Udinese in Italy\'s top tier.</p>
<p>Three seasons in Udine yielded 11 goals in 95 appearances, convincing Sampdoria to clinch his signature in the summer of 2016. International recognition as part of Portugal&rsquo;s Olympic squad followed, before Bruno captained the Under-21s at the UEFA European Championships in 2017.</p>
<p>After shining in a solitary season with Sampdoria, Bruno moved back home, signing for Sporting Clube de Portugal. Although he had mostly played in Italy as a deep midfielder, Fernandes now took on the role of playmaker at the Estadio Jose Alvalade, contributing 16 goals and 20 assists in his first Primeira Liga campaign.</p>
<p>That record, coupled with a Portuguese League Cup win, helped Fernandes gain his first senior international cap, and he was later selected for Fernando Santos&rsquo; 2018 World Cup squad in Russia.</p>
<p>Named Primeira Liga Player of the Year in July 2018, Bruno picked up where he left off the following season, hitting an incredible 20 league goals from midfield and assisting a further 13. The Lions claimed the Portuguese Cup and League Cup double and the midfielder, who was named club captain after Nani&rsquo;s departure, once again picked up Portugal&rsquo;s premier individual accolade.</p>
<p>He was part of the national team squad which won the inaugural UEFA Nations League in June 2019, only Portugal&rsquo;s second major trophy.</p>
<p>After a productive first half of 2019/20, during which he helped Sporting to the last 32 of the UEFA Europa League, he completed his move to Old Trafford on 30 January 2020. He made his Reds debut two days later, during the 0-0 draw with Wolverhampton Wanderers.</p>
<p>It wasn\'t long before the Portuguese\'s impact was felt. He delivered his first assist in just his second game &ndash; a 2-0 win at Chelsea &ndash; and then scored his first goal (from the penalty spot) on his third start. And that was just a taste of what was to come: Bruno scored 12 goals and provided eight assists before the end of the season, and was arguably the driving force behind United\'s impressive run to a third-place finish in the Premier League.</p>
<p>He was named the Sir Matt Busby Player of the Year for the season, despite playing just half of the campaign.</p>
<p>Bruno began 2020/21 in fine style, too, scoring a dramatic 100th-minute winner from the spot at Brighton. Fernandes was United\s - and maybe even the Premier League\'s - standout performer during the first half of the campaign, claiming the club\'s and league\'s Player of the Month awards for November and December.</p>
<p>In helping the Reds to a second-placed finish, and the Europa League final, Bruno scored 28 goals, overtaking Frank Lampard\'s record for a midfielder in a single season in the Premier League era. He picked up his second Sir Matt Busby Player of the Year trophy, in front of returning fans at Old Trafford, and also won the club\'s Goal of the Season prize for a spectacular effort against Everton.</p>
<p>In April 2022, Bruno signed a new long-term contract with club, rewarding his work since his arrival from Sporting. The deal is due to run until 2026, with the option of a further year.</p>', 'Portugal', '8 Sep 1994', 'Bruno', 'portugal.svg', '30 Jan 2020', 'Fernandes', '18', 'Midfielder', 'To play for United feels incredible. I can promise the fans I will give everything to help bring us success.', 'Bruno Fernandes took an unusual path to the top when compared to other Portuguese talents who have served Manchester United.', 'bruno.jpg', 'bruno-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('25', '50', '<p>It was at his boyhood club that van de Beek made his name on the world scene, as part of the thrilling Ajax side that reached the 2018/19 Champions League semi-finals. Though joining United at the relatively tender age of 23, his Ajax education meant he already possessed a polished all-round game and a wealth of experience.</p>
<p>Born on 18 April 1997 in Nijkerkerveen, the Netherlands, van de Beek began his football story with local side Veensche Boys and was later invited to join the famous Ajax academy in August 2014.</p>
<p>Donny made his debut for the club\'s reserve team, Jong Ajax, in January 2015 and, two months later, he was placed on the first-team bench for an Eredivisie match against ADO Den Haag. At the end of 2014/15, he won the AFC Ajax Talent of the Future award, to join a list of previous winners that includes Rafael van der Vaart, Wesley Sneijder, Daley Blind and Christian Eriksen.</p>
<p>His first-team debut arrived in November 2015, in a UEFA Europa League match against Celtic, and he finished the 2015/16 season with 10 senior appearances to his name. His first goal, coincidentally, was scored against Ole Gunnar Solskjaer&rsquo;s Molde, a month after his debut.</p>
<p>He truly established himself in the first-team set-up the following season, making 29 appearances as Ajax progressed to the Europa League final &ndash; where they were beaten 2-0 by Jose Mourinho&rsquo;s United in Stockholm. Van de Beek, who had recently turned 20, was a 70th-minute substitute in the match.   A senior international debut was achieved in 2017/18, in the Netherlands\' 1-0 defeat to England, and 35 more first-team games with Ajax added to his sense of progression.</p>
<p>But it was the following season where van de Beek and his fellow generation of Ajax academy talents really thrust themselves into the limelight, via the European stage. Impressively, Ajax reached the last four of the Champions League, beating Real Madrid and Juventus on their way to a semi-final clash with Tottenham Hotspur.</p>
<p>Van de Beek scored a nerveless goal in Juventus&rsquo;s Allianz Stadium to put them on the road to a 2-1 win in the second leg of the quarter-final, and then earned them a 1-0 advantage after the first leg against Tottenham, thanks to a similar finish.</p>
<p>Famously, a second-half hat-trick from Tottenham forward Lucas Moura would break Dutch hearts and deny Ajax what seemed a certain place in the Champions League final. But van de Beek and peers like Matthijs de Ligt, Frenkie de Jong and Hakim Ziyech were now established on the world stage, and attracting interest from high-profile suitors.</p>
<p>Ajax, as a club, would have to console themselves with the Eredivise title and the KNVB Cup.&#8232; De Ligt and de Jong left for Juventus and Barcelona, respectively, in the summer of 2019, but van de Beek stayed, and supplied eight goals and five assists in the following Eredivisie season, before the campaign was cancelled due to coronavirus.</p>
<p>On 2 September 2020, Ajax announced that a deal had been agreed with Manchester United for Donny&rsquo;s transfer. The midfielder, who can adopt any role in that area of the pitch, signed a five-year deal with the option to extend for a further year.</p>
<p>He scored on his Premier League debut, albeit in a 3-1 defeat to Crystal Palace, and went on to make 36 appearances in his debut campaign, as he tried to adjust to the English top flight in difficult circumstances, with no fans pesent.</p>
<p>On 31 January 2022, it was announced that Donny would join Everton on loan for the second half of the 2021/22 season. The Dutchman\'s loan spell with the Toffees began well, with six consecutive starts, but ongoing injury problems led to van de Beek missing a lot of matches.</p>
<p>The midfielder only featured for Everton once more before the end of his loan, scoring in the final Premier League match of the season at Arsenal, with the Merseysiders retaining their Premier League status.</p>
<p>The arrival of Erik ten Hag, his former boss in Amsterdam, presents the opportunity of a fresh start for the midfielder in Manchester.</p>', 'Netherlands', '18 Apr 1997', 'Donny', 'netherlands.svg', '2 Sep 2020', 'Van De Beek', '34', 'Midfielder', 'I am ready to take the next step in my career and there is no higher standard than Manchester United.', 'Short of graduating from the Manchester United Academy, there can be few better places to hone your skills as an aspiring footballer than at Ajax.', 'dvb.jpg', 'dvb-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('25', '170', '<p>After being a mainstay in the Reserves during 2016/17, he received a call-up to the first team towards the end of the campaign and made his debut away at Arsenal in May 2017.</p>
<p>Lancaster-born McTominay had just turned five when he first caught United&rsquo;s eye at the development centre in Preston. He progressed through the ranks with the Reds and, following a growth spurt during his Academy days and endless hours in the gym, McTominay&rsquo;s game has altered dramatically as he&rsquo;s got older. A player with great ability on the ball, he can also handle the physical demands in the middle of the park, snapping into tackles when needed, and he is useful in the air.</p>
<p>Since sharing no.10 duties with a certain Marcus Rashford in United&rsquo;s Under-16s, he has moved deeper into central midfield, viewed as his most natural position, where his strength has come in very useful.</p>
<p>McTominay enjoyed his first senior pre-season tour in the summer of 2017 and netted his first goal during the 3-0 friendly win over Valerenga. The midfielder was subsequently handed the no.39 shirt at the start of the 2017/18 season and, having made a real impression on his first Champions League start against Benfica at Old Trafford, has continued to make the most of further chances that have come his way with outstanding contributions in victories against Liverpool and Chelsea.</p>
<p>The midfielder received former manager Jose Mourinho&rsquo;s Player of the Season award at the end of a breakout season for the youngster, who will be hoping to go from strength to strength in the next campaign.</p>
<p>In the 2018/19 campaign McTominay continued to impress and showed his versatility by dropping into a deeper position of centre-back on occasion.</p>
<p>On 21 January 2019, Scott signed a contract extension with the Reds that will keep him at the club until 2023. &ldquo;Manchester United has been my life since the age of five and playing for the club I\'ve always supported is all I\'ve ever wanted to do,&rdquo; said the midfielder upon agreeing his new deal.</p>
<p>The Scotland international\'s progress has continued as he has managed to hold down a regular place and provide a goal threat from midfield, in addition to boundless energy and determination. His strike in the win over Norwich City in October 2019 was a landmark one for the club - the 2,000th United goal in the Premier League.</p>
<p>After suffering a knee ligament injury in our Boxing Day clash with Huddersfield, McTominay bounced back in style in February, scoring his first goal in European competition against Club Br&uuml;gge at Old Trafford. The Academy graduate also provided one of the great moments of the 2019/20 season few days later. Our no. 39 saw Manchester City keeper Ederson off his line and scored a brilliant goal from 35 yards out to secure a 2-0 Manchester Derby win in stoppage time.</p>
<p>In June, McTominay was delighted to sign a new contract with Manchester United until 2025, with the option of a further year.</p>
<p>&ldquo;All I have ever known is United and I hope that my passion for the club shows every time I go onto the pitch. I&rsquo;ll continue to give everything for this club whenever I pull on the shirt.&quot;</p>
<p>Scott captained the Reds for the first time during the Emirates FA Cup third-round tie with Watford in January 2021, and scored the winner in that game.</p>
<p>In the summer of 2021, McTominay was part of the first Scotland squad to compete in a major international tournament since 1998, when Steve Clarke\'s side featured in Euro 2020.</p>
<p>The Scot remained a regular throughout 2021/22, missing very few games as he racked up a further 37 appearances for his boyhood club. McTominay was on the scoresheet for the Reds against Burnley in December and scored the winner in our FA Cup third-round win over Aston Villa in January.</p>
<p>The occasional injury ruled the midfielder out of a handful of games, but for the most part, McTominay was a trusted performer for the Reds in 2021/22.</p>', 'Scotland', '8 Dec 1996', 'Scott', 'scotland.svg', '1 Jul 2012', 'McTominay', '39', 'Midfielder', 'You\'ve got to keep working hard. The moment you stop is when things can go bad for you.', 'An intelligent operator who can perform in midfield and attack, Scott McTominay was officially promoted to the senior squad at the start of the 2017/18 campaign.', 'mctom.jpg', 'mctom-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('26', '269', '<p>Martial began his career in the junior ranks of CO Les Ulis, where Henry and ex-Red Patrice Evra both started their illustrious careers. At the age of 14, he joined Lyon and became a regular for the France youth sides, earning a reputation as one of Europe&rsquo;s hottest prospects. His excellent potential was so obvious that Monaco paid &euro;5million for his signature in a transfer that rocked French football.</p>
<p>Anthony then joined the Reds on transfer deadline day during the summer of 2015 and made his mark by scoring an excellent debut goal as a substitute against Liverpool, which immediately won the love and respect of the fans. That famous strike later won the club&rsquo;s Goal of the Season award during the annual prize-giving night at Old Trafford, beating off competition from Marcus Rashford.</p>
<p>Martial finished the 2015/16 season as United&rsquo;s top scorer with 17 goals from 49 appearances and that included a dramatic added-time winner during the FA Cup semi-final victory over Everton, which led to earning a winners&rsquo; medal following the 2-1 extra-time win over Crystal Palace in the final. That wrapped up a superb maiden season in which the Reds forward emphasised his massive potential.</p>
<p>The 2016/17 campaign, his first under the management of Jose Mourinho, yielded eight goals and 42 appearances, plus three trophies in the FA Community Shield, EFL Cup and UEFA Europa League.</p>
<p>2017/18 saw the no.11 shift up a gear once more, his explosive pace and instinctive eye for goal making him a key part of United\'s attacking armoury. Either sharing attacking duties with Rashford or being unleashed as a front three with Marcus and Lukaku, Martial surpassed his goals total from the previous season. Five goals in United\'s opening eight games, plus a run of form in January meant that the Frenchman ended the season with 11 goals in all competitions.</p>
<p>Anthony enjoyed a good first half of the 2018/19 season and was voted our Player of the Month for October by fans after a series of impressive performances. On 31 January 2019, Martial signed a new contract, keeping him at the club until June 2024, with the option to extend for a further year.</p>
<p>Following Romelu Lukaku\'s move to Inter Milan, he switched back to United\'s no.9 jersey and quickly got off the mark for 2019/20 with the second goal in the 4-0 rout of Chelsea at Old Trafford, giving an early indication that he will thrive on the responsibility of playing down the middle and compensating for the lack of the Belgian\'s goals.</p>
<p>The Frenchman ended the 2019/20 season as United\'s top goalscorer with 23 goals, with 17 coming in the Premier League, his highest ever tally. As well, he set up 12 goals for his team-mates, resulting in 35 goal involvements in 48 appearances. Following his impressive season and attacking output, our no. 9 was voted as the Player\'s Player of the Year. That made Martial the first striker to receive the award since Wayne Rooney in the 2009/10 season.</p>
<p>Martial\'s involvement was reduced during the 2020/21 campaign as he faced fresh competition from new signing Edinson Cavani, who was Paris Saint-Germain\'s record goalscorer when he left the French club. Anthony made 36 appearances but scored only seven goals &ndash; two of which came as a sub in the Premier League record-equalling 9-0 win over Southampton.</p>
<p>Injury problems caused the no.9\'s outings to dwindle further in the first half of 2021/22 and his only goal came in a 1-1 draw with Everton at Old Trafford. After regaining fitness under interim manager Ralf Rangnick, he expressed a desire to play more regular first-team football.</p>
<p>After moving on loan to Spanish club Sevilla in January 2022, Anthony made made 12 appearances across La Liga and the Europa League. Injuries hampered the Frenchman\'s time in Spain, and he recorded one goal and one assist before returning to Manchester at the end of the season.</p>', 'France', '5 Dec 1995', 'Anthony', 'france.svg', '1 Sep 2015', 'Martial', '9', 'Forward', 'I love Manchester United, I love the fans, they give me a lot of joy.', 'A forward who is often compared to Premier League legend Thierry Henry, another former Monaco man, Anthony Martial has all of the tools needed to shine at Manchester United.', 'martial.jpg', 'martial-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('24', '303', '<p>The homegrown youth product has already come such a long way in a short time and having the happy knack of scoring on his debuts has helped. He netted twice against Midtjylland when thrust into the spotlight in a Europa League tie and followed it up with a brace against Arsenal on his Premier League bow.</p>
<p>The fleet-footed forward found the net on his first England appearance, within a couple of minutes of the 2-1 win over Australia at Sunderland&rsquo;s Stadium of Light to become the youngest man to score on his Three Lions debut, beating Tommy Lawton&rsquo;s 1938 record.</p>
<p>A famous derby winner at Manchester City and crucial FA Cup replay goal on the way to winning the trophy under Louis van Gaal continued his sharp upward trajectory, which continued with representing his country at Euro 2016. A new contract until 2020, with the option of a further year, was just reward for his meteoric rise to stardom.</p>
<p>After being involved in 53 games in all competitions in the following season, getting off the mark when coming off the bench to hit an injury-time winner at Hull City early in the campaign, it was obvious he was no flash in the pan. Indeed, Jose Mourinho continued to show faith in the youngster as he was constantly involved and bagged a memorable double in a 2-1 home victory against Liverpool in 2018.</p>
<p>Becoming ever more important for club and country, he nervelessly fired home a penalty in the dramatic shoot-out win over Colombia at the World Cup finals and would later show similar steel to power the injury-time spot-kick past Gianluigi Buffon to knock Paris Saint-Germain out of the 2018/19 Champions League at the Parc des Princes.</p>
<p>Such mental fortitude has quickly become part of Rashford&rsquo;s make-up as he has shouldered a lot of responsibility in attack and ran tirelessly in games, defending from the front and displaying great energy. Ole Gunnar Solskjaer appears to relish helping to mentor the striker and is working on honing his finishing prowess as the Academy product develops his game even further.</p>
<p>Following Romelu Lukaku\'s departure to Inter Milan, it was suggested he would need to improve his goal output and he delivered in the opening game of the 2019/20 season with a brace in the 4-0 defeat of Chelsea, maintaining his good record against other top-six sides. A landmark 50th strike for the Reds came in October, when he atoned for having a penalty saved by Tim Krul when expertly finishing Daniel James\'s through ball.</p>
<p>The goals continued to flow for the homegrown product as he scooped the club\'s Player-of-the-Month award for November and December, and also the overall PFA Premier League prize for the last month of 2019. He marked his 200th appearance for the club with a double in a 4-0 victory over Norwich City in January.</p>
<p>A stress fracture to his back ruled him out of action prior to the suspension of football during the COVID-19 pandemic, but Rashford used his time out to campaign against homelessness and child hunger in the United Kingdom &ndash; work for which he would go on to receive an MBE.</p>
<p>While receiving wider acclaim for his actions off the pitch, Marcus continued to impress on it, scoring his first United hat-trick against RB Leipzig in the Champions League on the way to registering 21 goals in all competitions in 2020/21 &ndash; just one fewer than in the previous season.</p>
<p>He captained the England senior side for the first time in a friendly with Romania before Euro 2020, scoring a penalty which brought him to 100 goals for club and country, at the still tender age of 23.</p>
<p>Following the Euros, Rashford had surgery on an ongoing shoulder issue, which ruled the winger out for the beginning of the 2021/22 season. The attacker missed the first seven Premier League matches and returned to action with a goal off the bench away to Leicester in October 2021.</p>
<p>Despite not hitting the heights of his previous seasons Rashford was regularly utilised by Ole Gunnar Solskjaer and then by interim manager Ralf Rangnick, making 32 appearances in total across the season. The winger scored in consecutive matches off the bench against Brentford and West Ham in February, but starts became more sporadic for the England international as the season drew to a close.</p>', 'England', '31 Oct 1997', 'Marcus', 'england.svg', '1 Jul 2014', 'Rashford', '10', 'Forward', 'I have always been a United fan, so to be playing in the first team really is a dream come true.', 'Marcus Rashford was thrust into the senior spotlight in February 2016 – with spectacular results – and has not looked back since.', 'rashford.jpg', 'rashford-bg.png');

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('22', '38', '<p>After four fantastic seasons at Borussia Dortmund in Germany&rsquo;s Bundesliga, Sancho joined the Reds in July 2021; a 21-year-old mature beyond his years. His play is fearless, skilful and expressive and he thrives when isolating defenders and taking them on, one-on-one.</p>
<p>Born in London on 25 March 2000, Sancho grew up in Kennington, idolising Ronaldinho and playing cage football amid the capital\'s high-rise buildings. He joined Watford\'s youth set-up aged seven and moved into the club\'s partner school as a boarder four years later, thus avoiding the long travel time across from south London.</p>
<p>Aged 14, Sancho left the capital and its surrounds, joining Manchester City where he excelled in the youth set-up. Regularly dominating games, it quickly became clear that Sancho was one of English football\'s most exciting young talents, a fact confirmed when he was named Player of the Tournament at the Under-17 European Championship in May 2017.</p>
<p>In the summer of that year, Sancho left England before he\'d made a single senior appearance, bravely moving abroad in search of first-team football, which he found at Borussia Dortmund after an &pound;8m transfer to Germany.</p>
<p>The London-born winger gradually settled into life in a new country and, despite immediately handing the 17-year-old the number seven shirt, Dortmund were initially cautious in their approach. Sancho made his Bundesliga debut as a late substitute on 21 October 2017, his first start the following January, and then truly ignited the spark with a goal &ndash; his first in the league &ndash; and two assists in a 4-0 win against Bayer Leverkusen in April 2018.</p>
<p>From there, he kicked on in stunning fashion, with October 2018 being an outstanding month. Within the space of a few weeks, Sancho made his England debut, became the first player born in the 2000s to score in the UEFA Champions League when he struck against Atletico Madrid, and was named Bundesliga Player of the Month for the first time.</p>
<p>A place in the 2018/19 Bundesliga Team of the Season was inevitable after a record-breaking campaign from the teenager, in which he scored 12 goals and assisted a further 14. Such proficiency in attack catapulted his reputation skywards and he delivered once again in 2019/20, as he was named in the Team of the Season for a second consecutive year after posting a stunning 17 goals and 17 assists in 32 league games. A hat-trick &ndash; his first in senior football &ndash; against SC Paderborn in May 2020 was made more notable by the celebration for his first goal, in which Sancho revealed a T-shirt reading \'Justice for George Floyd\'. The gesture demonstrated the young man\'s desire to use football as a driver for social change, something he has continued to do. A previous project saw him help build a new football pitch in his old neighbourhood in south London.</p>
<p>On 13 May 2021, the Englishman wrapped up his career in Germany in the perfect fashion when he scored a double against RB Leipzig to help Borussia Dortmund win the DFB-Pokal [the German Cup]. He scored 50 goals and made 64 assists in 137 games for Dortmund and that incredible record meant it was no surprise United wanted to sign him. A fee agreement was announced on 1 July 2021, while Sancho was representing England at Euro 2020, with the transfer being formally completed three weeks later.</p>
<p>&ldquo;Football is about expressing yourself,&rdquo; Sancho has explained in the past. He\'s a player who plays for fun and to excite, without fear and with a burning desire to beat his man.</p>
<p>Jadon\'s debut season at Old Trafford was mixed, with the winger remaining patient before being handed his first United start, in our 1-0 away win at Wolves on 29 August 2021. Sancho scored his first goal for the Reds in a 1-1 away draw with Chelsea at the end of November, but he didn\'t score again until February.</p>
<p>However, Jadon\'s output increased and we then saw his true ability, with the winger recording two goals and three assists across a six-match period. The winger missed the latter stages of the season due to tonsillitis, but finished his debut campaign with the Reds having racked up 38 appearances in all competitions, with five goals and three assists, and the promise of much more to come.</p>', 'England', '25 Mar 2000', 'Jadon', 'england.svg', '23 Jul 2021', 'Sancho', '25', 'Forward', 'Growing up, United was one of the biggest clubs that everyone knows. So I\'m very happy to be wearing this jersey now.', 'In Jadon Sancho, Manchester United have a thrilling, tricky winger whose game is inspired by the dancing samba style of Brazil\'s greatest forwards and the gritty street football of south London.', 'sancho.jpg', 'sancho-bg.png');