use manutd;

insert into `manutd`.`players` (`age`, `appearances`, `biography`, `country`, `date_of_birth`, `first_name`, `flag`, `joined`, `last_name`, `number`, `position`, `slogan`, `title`, `avatar`, `background`)
	values ('37', '330', '<p>The world-famous forward has regularly adapted his game over the last two decades, transforming himself from the tricky, mercurial winger that arrived at United in 2003 to a poacher of the highest quality in recent years.</p>
<p>Ronaldo moved away from his home and family on the Portuguese island of Madeira to join Sporting Lisbon\'s academy and he made his first-team debut as a 16-year-old. He was being courted by several clubs, most notably Arsenal, when Sir Alex Ferguson decided to bring the talented teenager to Old Trafford after the Reds visited Sporting for a pre-season friendly in August 2003. Still spindly but with jaw-dropping footwork, Cristiano made such a great impression in that game, United&rsquo;s players on the flight home called for him to be signed. A deal was quickly done and Ronaldo was handed the iconic no.7 shirt vacated by David Beckham earlier in the summer.</p>
<p>Aged 18 and entrusted with the club&rsquo;s most famous shirt, Ronaldo made his first appearance as a substitute in a home win over Bolton Wanderers. George Best described it as the most exciting debut he&rsquo;d seen and comparisons between the two developed throughout Cristiano&rsquo;s first season at Old Trafford. His feet were quick, his body agile and his shot powerful. He could frustrate as much as he excited, his undoubted ability yet to be polished by the United coaching staff, but he ended the season with a goal in the FA Cup final against Millwall to win the first of nine trophies in six years.</p>
<p>Fellow teenage superstar Wayne Rooney joined the club in 2004 and over the next two years, the new-look team developed but titles were still going the way of Arsenal and Chelsea. After an altercation between Rooney and Ronaldo at the 2006 World Cup, it seemed the latter would end his time in England prematurely. But, led by Sir Alex, the United family closed the circle and made sure the pair felt looked after. Such faith would be repaid in spades and the Reds romped to three consecutive league titles.</p>
<p>The era of renewed success began as United thrashed Fulham 5-1 on the opening day of the 2006/07 season, with two goals from Rooney and one from Ronaldo. As Sir Alex\'s men claimed a first league title in four years, both players broke the 20-goal barrier for the first time, each of them scoring 23 in all competitions. The Reds came close to achieving a second Treble, losing in the FA Cup final and UEFA Champions League semi-final. More silverware seemed an inevitability for the team and Ronaldo was already building a collection of individual honours. By winning the PFA Players&rsquo; Player of the Year, Fans&rsquo; Player of the Year, Young Player of the Year and FWA Footballer of the Year awards, he became the first man to lift all four in the same year.</p>
<p>In the 2007/08 season, Ronaldo&rsquo;s desperate desire to be the world&rsquo;s best player drove him to new heights and United ascended with him. He scored a remarkable 42 goals as Sir Alex\'s men won a double of the Premier League title and Champions League. The Portugal international - soon to be named captain of his country - scored decisive goals time and time again in both competitions, including our only goal in the Moscow final as the Reds were crowned kings of European club football. The individual accolades all fell to Cristiano once again.</p>
<p>It soon became clear that Ronaldo sought to fulfil his childhood dream of playing for Real Madrid. Sir Alex convinced him to stay at United for one more year, enough time for him to help the Reds win a third consecutive Premier League title and become world club champions in Tokyo and, on a personal level, be crowned Ballon d&rsquo;Or winner for the first time, aged 23. After playing in a second consecutive Champions League final, as United were beaten by a brilliant Barcelona side in Rome, Ronaldo bid farewell to Manchester and moved to Madrid.</p>
<p>On 6 July 2009, 80,000 people crammed into the Santiago Bernabeu to watch the world&rsquo;s most expensive footballer being unveiled. An astonishing 450 goals in 438 games followed as Ronaldo became the all-time top goalscorer at Real Madrid. Along the way, he helped the Spanish giants to achieve the much sought-after La Decima - their 10th European Cup, in 2014 - and win 15 major trophies in total. As he did with United, Cristiano won every trophy available to Real &ndash; and most of them on more than occasion.</p>
<p>After Ronaldo had accomplished everything there was to achieve at Real Madrid, Juventus paid &euro;100m to sign him in 2018. It was the most expensive transfer by an Italian club and the highest fee ever paid for a player older than 30. He won five trophies in three years and was Serie A\'s top goalscorer last season, 2020/21, with 29 goals for the Old Lady.</p>
<p>Upon completing his second transfer to Old Trafford, the five-time Ballon d&rsquo;Or winner told United fans the club has &ldquo;always had a special place in my heart.&rdquo;</p>
<p>His former team-mate and now manager Ole Gunnar Solskjaer said: &ldquo;You run out of words to describe Cristiano. Ronaldo\'s return demonstrates the unique appeal of this club and I am absolutely delighted he is coming home."</p>
<p>As for the international stage, Ronaldo has represented Portugal at 11 major tournaments and scored in them all. He captained the Selecao to glory in the 2016 European Championships and 2019 UEFA Nations League, having worn the armband for the last 13 years. At UEFA Euro 2020, he won the Golden Boot.</p>
<p>On 1 September 2021, the day after his transfer back to United was finalised, Cristiano set a new men\'s international goals record by scoring twice for Portugal against Republic of Ireland to take his tally to 111 - two clear of the previous holder, Iran legend Ali Daei.</p>
<p>Ronaldo hit the ground running on his return to the Reds, scoring twice on his second debut in our 4-1 win over Newcastle at Old Trafford on 11 September 2021. The Portuguese superstar went on to score 24 goals in all competitions for United in 2021/22, finishing second to Mohamed Salah and Heung-min Son in the race for the Premier League Golden Boot.</p>
<p>In June, our no.7 was awarded the Sir Matt Busby Player of the Year award, equalling David de Gea\'s record of winning the accolade on four occasions. This achievement was preceded by Ronaldo\'s five Player of the Month awards and 10 Man of the Match wins, which were awarded for his match-winning exploits, such as his remarkable hat-tricks against Tottenham and Norwich.</p>
<div class="row player-content__cta ">
<p>At the age of 37, Ronaldo finished 2021/22 having made an incredible 38 appearances for the Reds in all competitions, and he\'s showing no signs of slowing down.</p>
</div>', 'Portuguese', '5 Feb 1985', 'Cristiano', 'portugal.svg', '31 Aug 2021', 'Ronaldo', '7', 'Forward', '"History has been written in the past and history will be written once again. You have my word."',  'Cristiano Ronaldo returned to Manchester United in 2021 as one of the greatest footballers of all time, with a trophy-littered career that is almost beyond the realms of belief in its consistency, longevity, and success.', 'ronaldo.png', 'ronaldo-bg.png');