use manutd;

-- 1.Men
insert into products value (1,"Product ID: 12093042.Inner back neck signoff.Devil signoff below back collar.Regular fit.Ribbed crewneck.100% recycled polyester piqué.Moisture absorbing.Ribbed cuffs.AEROREADY","manchester-united-home-shirt.jpg","Manchester United Home Shirt 2021-22",25000,1);
insert into products value (2,"Product ID: 12093042.Inner back neck signoff.Devil signoff below back collar.Regular fit.Ribbed crewneck.100% recycled polyester piqué.Moisture absorbing.Ribbed cuffs.AEROREADY","manchester-united-home-shirt-2021-22-with-ronaldo-7-printing.jpg","Manchester United Home Shirt 2021-22 with Ronaldo 7 printing",43000,1);
insert into products value (3,"Product ID: 12052548.Regular fit.Ribbed V-band collar.100% recycled polyester mock eyelet.Moisture absorbing","manchester-united-third-shirt-2021-22_ss4_man.jpg","Manchester United Third Shirt 2021-22",34000,1);
insert into products value (4,"Product ID: 12085065.Manchester United embroidered crest.Loose fit.Crewneck.100% recycled polyester doubleknit.Mesh inserts","manchester-united-teamgeist-jersey-black.jpg","Manchester United Teamgeist Jersey - Black",30000,1);
insert into products value (5,"Product ID: 12084800.Manchester United heat-applied crest.Regular fit.Half zip with hood.100% recycled polyester French terry","manchester-united-training-hoodie-red.jpg","Manchester United Training Hoodie - Red",39000,1);
insert into products value (6,"Product ID: 12052603.Manchester United woven crest.Regular fit.Ribbed crewneck.100% recycled polyester doubleknit","manchester-united-away-shirt-2021-22.jpg","Manchester United Away Shirt 2021-22",25000,1);
insert into products value (7,"Product ID: 11989172.100% Polyester.Unisex","manchester-united-1999-shirt.jpg","Manchester United 1999 Shirt",67000,1);
-- 2.Women
insert into products value (8,"Product ID: 13313231.Manchester United heat-transferred crest.Goal net-inspired engineered fabric insert.Slim fit.Quarter zip with ribbed stand-up collar.100% recycled polyester French terry.Moisture-absorbing AEROREADY","manchester-united-training-top-navy-womens_ss4.jpg","Manchester United Training Top - Navy - Womens",77000,2);
insert into products value (9,"Product ID: 13313282.Regular fit.Ribbed V-neck.Ribbed V-neck.Moisture-absorbing AEROREADY.Manchester United heat-transferred crest","manchester-united-training-jersey-navy-womens_ss4_p.jpg","manchester-united-training-jersey-navy-womens_ss4_p",53000,2);
insert into products value (10,"Product ID: 12075904.Inner back neck signoff.Devil signoff below back collar.Regular fit.100% recycled polyester piqué","manchester-united-cup-home-shirt-2021-22-womens-with-maguire-5-printing.jpg","Manchester United Cup Home Shirt 2021-22-Womens with Maguire 5 printing",74000,2);
insert into products value (11,"Product ID: 12094222.Regular fit.Ribbed V-band collar.100% recycled polyester engineered","manchester-united-third-authentic-shirt-2021-22-womens-with-ronaldo-7-printing.jpg","Manchester United Third Authentic Shirt 2021-22-Womens with Ronaldo 7 printing",67000,2);
insert into products value (12,"Product ID: 13303120.Supports the Better Cotton Initiative.Loose fit.Drawcord-adjustable hood.67% cotton, 33% recycled polyester doubleknit.Kangaroo pocket","manchester-united-adidas-3-stripe-future-icons-hoodie-almost-pink-womens.jpg","Manchester United adidas 3-Stripe Future Icons Hoodie - Almost Pink - Womens",73000,2);
insert into products value (13,"Product ID: 13313277.Regular fit.Ribbed Henley collar with button closure.58% cotton, 42% recycled polyester piqué","manchester-united-training-polo-navy.jpg","Manchester United Training Polo - Navy",53000,1);
insert into products value (14,"Product ID: 12070086.Material: '-Plain weave-DWR - PFC C6 - Exception.Indonesia","halo-blue-womens.jpg","Manchester United Adidas Terrex Gtx Paclite Jacket - Power Berry/Halo Blue - Womens",131000,2);
insert into products value (15,"Product ID: 12052544.Inner back neck signoff.Devil signoff below back collar.Regular fit.Ribbed crewneck.100% recycled polyester piqué.Moisture absorbing","manchester-united-home-shirt-2021-22-long-sleeve.jpg","Manchester United Home Shirt 2021-22-Long Sleeve",37000,1);
insert into products value (16,"Product ID: 12093320.100% cotton.Player name and number.Officially licensed","manchester-united-adidas-cristiano-ronaldo-t-shirt-red-womens.jpg","Manchester United adidas Cristiano Ronaldo T-Shirt - Red - Womens",19000,2);
-- 3.Kids
insert into products value (17,"Product ID: 12052594.Shorts: Elastic waist.Includes one pair of crew-length socks.Regular fit.Ribbed crewneck.100% recycled polyester doubleknit.Moisture absorbing.Jersey: Ribbed cuffs","manchester-united-home-minikit-2021-22_ss4_kids.jpg","Manchester United Home Minikit 2021-22",19000,3);
insert into products value (18,"Product ID: 12052587.Includes one pair of crew-length socks.Manchester United heat-applied crest.Regular fit.Jersey: 100% recycled polyester mock eyelet","manchester-united-third-minikit-2021-22_ss4-kids.jpg","Manchester United Third Minikit 2021-22",22000,3);
insert into products value (19,"Product ID: 12093045.Shorts: Elastic waist.Includes one pair of crew-length socks.Regular fit.Ribbed crewneck.100% recycled polyester doubleknit","manchester-united-home-minikit-2021-22-with-ronaldo-7.jpg","Manchester United Home Minikit 2021-22 with Ronaldo 7 printing",37000,3);
insert into products value (20,"Product ID: 12075252.Shorts: Elastic waist.Includes one pair of crew-length socks.Regular fit.Ribbed crewneck.100% recycled polyester doubleknit","manchester-united-home-minikit-2021-22-with-rashford-10-printing.jpg","Manchester United Home Minikit 2021-22 with Rashford 10 printing",37000,3);
insert into products value (21,"Product ID: 12093322.100% cotton.100% cotton","manchester-united-adidas-cristiano-ronaldo-t-shirt-red-kids.jpg","Manchester United adidas Cristiano Ronaldo T-Shirt - Red - Kids",9000,3);
insert into products value (22,"Product ID: 13303141.Zip pocket on chest.Reflective details.Supports the Better Cotton Initiative.Regular fit.Full zip with stand-up collar","black-boys_ss4.jpg","Manchester United adidas XFG Full Zip Jacket - Black / Red - Boys",61000,3);
insert into products value (23,"Product ID: 13313237.Jacket: Elastic cuffs and hem.Pants: Elastic waist and ankle zips.Regular fit.Full zip with stand-up collar.100% recycled polyester plain weave","manchester-united-training-presentation-tracksuit-navy-infants.jpg","Manchester United Training Presentation Tracksuit - Navy - Infants",77000,3);
insert into products value (24,"Product ID: 12075253.Shorts: Elastic waist.Ribbed crewneck.100% recycled polyester doubleknit","manchester-united-home-minikit-2021-22-with-lindelof-2-printing.jpg","Manchester United Home Minikit 2021-22 with Lindelof 2 printing",37000,3);
-- 4.Baby
insert into products value (25,"Product ID: 12060100.Material: 100% Cotton.China","blue-baby.jpg","Manchester United 2 Pack Home and Away Kit Bodysuits - Blue - Baby",21000,4);
insert into products value (26,"Product ID: 12060100.Material: 100% Cotton.China","red-baby.jpg","Manchester United 2 Pack Home and Away Kit Bodysuits - Blue - Baby",21000,4);
insert into products value (27,"Product ID: 12061754.Material: Main: 100% Ootton, Rib: 96% Cotton, 4% Elastane.China","manchester-united-home-kit-sleepsuit-red-baby.jpg","Manchester United Home Kit Sleepsuit - Red - Baby",17000,4);
insert into products value (28,"Product ID: 12061755.Material: Main: 100% Ootton, Rib: 96% Cotton, 4% Elastane.China","manchester-united-third-kit-romper-blue-baby.jpg","Manchester United Third Kit Romper - Blue - Baby",17000,4);
insert into products value (29,"Product ID: 13303118.Supports the Better Cotton Initiative.Regular fit.Tee: Ribbed crewneck.100% cotton single jersey","-red-infants.jpg","Manchester United adidas 3-Stripe Sports Set - Blue / Red - Infants",38000,4);
insert into products value (30,"Product ID: 12061800.Material: Outer 100% Nylon, Padding: 100% Polyester, Binding: 83% Polyamide, 17% Elastane.China","ecru-baby.jpg","Manchester United Sherpa Lined Gilet - Red/Ecru - Baby",25000,4);